spring.application.name=SpringBootWeb

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:mem:springBootWeb
spring.datasource.username=<your_username>
spring.datasource.password=<your_password>
